import { Platform, StyleSheet } from 'react-native';

import { INTER_FONT } from '../../../theme/interFontCdn';
import { PROPERTIES_SCREEN_BG } from '../constants/propertyListFilters';

export const wizardColors = {
    background: PROPERTIES_SCREEN_BG,
    white: '#FFFFFF',
    borderGrey: '#EAEAEA',
    dashedBorder: '#DCDCD2',
    dark: '#111111',
    subtle: '#888888',
    faint: '#C4C4C4',
    success: '#1E8E3E',
    handle: '#D8D8D8',
    footerBtn: '#EBEBE4',
};

export const createPropertyStyles = StyleSheet.create({
    overlay: {
        flex: 1,
        justifyContent: 'flex-end',
        backgroundColor: 'rgba(0, 0, 0, 0.45)',
    },
    sheet: {
        backgroundColor: wizardColors.background,
        borderTopLeftRadius: 24,
        borderTopRightRadius: 24,
        maxHeight: '92%',
        minHeight: '72%',
        paddingBottom: Platform.OS === 'ios' ? 0 : 8,
        ...Platform.select({
            android: { elevation: 16 },
            ios: {
                shadowColor: '#000',
                shadowOffset: { width: 0, height: -4 },
                shadowOpacity: 0.12,
                shadowRadius: 12,
            },
        }),
    },
    dragHandle: {
        width: 40,
        height: 4,
        backgroundColor: wizardColors.handle,
        borderRadius: 2,
        alignSelf: 'center',
        marginTop: 12,
        marginBottom: 4,
    },
    header: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingHorizontal: 24,
        paddingTop: 12,
        paddingBottom: 16,
    },
    title: {
        fontFamily: INTER_FONT.bold,
        fontSize: 22,
        color: wizardColors.dark,
    },
    stepIndicator: {
        fontFamily: INTER_FONT.medium,
        fontSize: 13,
        color: wizardColors.subtle,
        marginTop: 4,
    },
    closeBtn: {
        width: 40,
        height: 40,
        borderRadius: 20,
        backgroundColor: '#F0F0EA',
        justifyContent: 'center',
        alignItems: 'center',
    },
    progressRow: {
        flexDirection: 'row',
        paddingHorizontal: 24,
        gap: 6,
        marginBottom: 16,
    },
    progressSegment: {
        flex: 1,
        height: 3,
        backgroundColor: '#E0E0D8',
        borderRadius: 2,
    },
    progressSegmentActive: {
        backgroundColor: wizardColors.dark,
    },
    body: {
        paddingHorizontal: 20,
        paddingBottom: 24,
    },
    stepCardActive: {
        backgroundColor: wizardColors.white,
        borderRadius: 16,
        padding: 20,
        marginBottom: 16,
        ...Platform.select({
            android: { elevation: 1 },
            ios: {
                shadowColor: '#000',
                shadowOffset: { width: 0, height: 2 },
                shadowOpacity: 0.04,
                shadowRadius: 8,
            },
        }),
    },
    stepHeaderRow: {
        flexDirection: 'row',
        alignItems: 'flex-start',
        marginBottom: 18,
    },
    stepBodyFlush: {
        marginTop: 2,
    },
    stepCircleActive: {
        width: 28,
        height: 28,
        borderRadius: 14,
        backgroundColor: '#F0F0EA',
        justifyContent: 'center',
        alignItems: 'center',
        marginRight: 12,
    },
    stepCircleActiveDone: {
        backgroundColor: wizardColors.dark,
    },
    stepCircleTextActive: {
        fontFamily: INTER_FONT.bold,
        fontSize: 12,
        color: wizardColors.dark,
    },
    stepHeaderText: {
        flex: 1,
    },
    stepTitleActive: {
        fontFamily: INTER_FONT.bold,
        fontSize: 16,
        color: wizardColors.dark,
        marginBottom: 4,
    },
    stepSubtitleActive: {
        fontFamily: INTER_FONT.medium,
        fontSize: 13,
        color: wizardColors.subtle,
    },
    stepCardSummary: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: wizardColors.white,
        borderRadius: 16,
        padding: 16,
        marginBottom: 12,
        borderWidth: 1,
        borderColor: '#F0F0F0',
    },
    stepCircleCompleted: {
        width: 28,
        height: 28,
        borderRadius: 14,
        backgroundColor: wizardColors.success,
        justifyContent: 'center',
        alignItems: 'center',
        marginRight: 12,
    },
    stepSummaryText: {
        flex: 1,
    },
    stepSummaryLabel: {
        fontFamily: INTER_FONT.semiBold,
        fontSize: 10,
        color: wizardColors.subtle,
        marginBottom: 2,
        letterSpacing: 0.5,
    },
    stepSummaryValue: {
        fontFamily: INTER_FONT.bold,
        fontSize: 15,
        color: wizardColors.dark,
    },
    editBtn: {
        fontFamily: INTER_FONT.bold,
        fontSize: 14,
        color: wizardColors.dark,
        paddingLeft: 10,
    },
    stepCardInactive: {
        flexDirection: 'row',
        alignItems: 'center',
        padding: 16,
        borderRadius: 16,
        borderWidth: 1,
        borderColor: wizardColors.dashedBorder,
        borderStyle: 'dashed',
        marginBottom: 12,
    },
    stepCircleInactive: {
        width: 28,
        height: 28,
        borderRadius: 14,
        borderWidth: 1,
        borderColor: wizardColors.dashedBorder,
        justifyContent: 'center',
        alignItems: 'center',
        marginRight: 12,
    },
    stepCircleTextInactive: {
        fontFamily: INTER_FONT.bold,
        fontSize: 12,
        color: wizardColors.faint,
    },
    stepTitleInactive: {
        fontFamily: INTER_FONT.semiBold,
        fontSize: 15,
        color: wizardColors.faint,
        flex: 1,
    },
    fields: {
        gap: 12,
    },
    panel: {
        borderWidth: 1,
        borderColor: '#E8E8E3',
        borderRadius: 14,
        paddingHorizontal: 16,
        paddingTop: 18,
        paddingBottom: 6,
        backgroundColor: '#FCFCFA',
    },
    panelRow: {
        flexDirection: 'row',
        alignItems: 'flex-start',
        marginBottom: 18,
        gap: 14,
    },
    panelRowTight: {
        marginBottom: 18,
    },
    panelRowLast: {
        marginBottom: 12,
    },
    panelCol: {
        flex: 1,
        minWidth: 0,
    },
    panelColSpacer: {
        flex: 1,
        minWidth: 0,
    },
    field: {
        width: '100%',
    },
    fieldLabel: {
        fontFamily: INTER_FONT.bold,
        fontSize: 14,
        lineHeight: 18,
        color: wizardColors.dark,
        marginBottom: 10,
        minHeight: 36,
    },
    fieldRequired: {
        color: '#D14343',
        fontFamily: INTER_FONT.bold,
    },
    fieldInput: {
        height: 46,
        borderWidth: 1,
        borderColor: '#E0E0DC',
        borderRadius: 8,
        paddingHorizontal: 14,
        fontFamily: INTER_FONT.medium,
        fontSize: 15,
        color: wizardColors.dark,
        backgroundColor: wizardColors.white,
    },
    areaRowFull: {
        flexDirection: 'column',
        alignItems: 'stretch',
    },
    areaControlRow: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 8,
        width: '100%',
    },
    areaSelectControl: {
        flex: 1,
        flexDirection: 'row',
        alignItems: 'center',
        minHeight: 52,
        paddingHorizontal: 14,
        paddingVertical: 12,
        borderWidth: 1,
        borderColor: '#E0E0DC',
        borderRadius: 8,
        backgroundColor: wizardColors.white,
        gap: 8,
    },
    areaSelectControlFilled: {
        borderColor: '#C8C8C0',
    },
    areaSelectValue: {
        flex: 1,
        fontFamily: INTER_FONT.medium,
        fontSize: 15,
        lineHeight: 20,
        color: wizardColors.dark,
        minWidth: 0,
    },
    areaActionBtn: {
        width: 52,
        height: 52,
        flexShrink: 0,
        borderRadius: 8,
        borderWidth: 1,
        borderColor: '#E0E0DC',
        backgroundColor: wizardColors.white,
        alignItems: 'center',
        justifyContent: 'center',
    },
    selectControl: {
        flexDirection: 'row',
        alignItems: 'center',
        borderWidth: 1,
        borderColor: '#E0E0DC',
        borderRadius: 8,
        paddingHorizontal: 14,
        paddingVertical: 12,
        backgroundColor: wizardColors.white,
        minHeight: 46,
    },
    selectValue: {
        flex: 1,
        fontFamily: INTER_FONT.medium,
        fontSize: 15,
        lineHeight: 20,
        color: wizardColors.dark,
        minWidth: 0,
    },
    selectPlaceholder: {
        fontFamily: INTER_FONT.regular,
        color: '#9A9A9A',
    },
    selectChevron: {
        width: 28,
        height: 28,
        alignItems: 'center',
        justifyContent: 'center',
        marginLeft: 4,
    },
    stackedField: {
        flexDirection: 'row',
        alignItems: 'center',
        borderWidth: 1,
        borderColor: wizardColors.borderGrey,
        borderRadius: 12,
        paddingHorizontal: 16,
        paddingVertical: 12,
        backgroundColor: wizardColors.white,
    },
    stackedBody: {
        flex: 1,
    },
    stackedLabel: {
        fontFamily: INTER_FONT.medium,
        fontSize: 11,
        color: wizardColors.subtle,
        marginBottom: 2,
    },
    stackedText: {
        fontFamily: INTER_FONT.medium,
        fontSize: 15,
        color: wizardColors.dark,
        padding: 0,
        margin: 0,
    },
    stackedPlaceholder: {
        color: wizardColors.subtle,
    },
    stackedIcon: {
        marginLeft: 10,
    },
    mediaBox: {
        borderWidth: 1,
        borderColor: wizardColors.dashedBorder,
        borderStyle: 'dashed',
        borderRadius: 12,
        padding: 30,
        alignItems: 'center',
        backgroundColor: wizardColors.white,
    },
    mediaBoxText: {
        fontFamily: INTER_FONT.medium,
        fontSize: 13,
        color: wizardColors.subtle,
        marginTop: 8,
    },
    footer: {
        paddingHorizontal: 24,
        paddingTop: 8,
        paddingBottom: Platform.OS === 'ios' ? 34 : 24,
        backgroundColor: wizardColors.background,
        borderTopWidth: 1,
        borderTopColor: '#EBEBEB',
    },
    primaryBtn: {
        backgroundColor: wizardColors.footerBtn,
        borderRadius: 12,
        paddingVertical: 16,
        alignItems: 'center',
    },
    primaryBtnEnabled: {
        backgroundColor: wizardColors.dark,
    },
    primaryBtnText: {
        fontFamily: INTER_FONT.bold,
        fontSize: 16,
        color: wizardColors.subtle,
    },
    primaryBtnTextEnabled: {
        color: wizardColors.white,
    },
    pickerOverlay: {
        flex: 1,
        justifyContent: 'flex-end',
        backgroundColor: 'rgba(0, 0, 0, 0.4)',
    },
    pickerSheet: {
        backgroundColor: wizardColors.background,
        borderTopLeftRadius: 20,
        borderTopRightRadius: 20,
        maxHeight: '55%',
        paddingBottom: Platform.OS === 'ios' ? 24 : 16,
    },
    pickerHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingHorizontal: 20,
        paddingTop: 16,
        paddingBottom: 12,
        borderBottomWidth: 1,
        borderBottomColor: '#EBEBEB',
    },
    pickerTitle: {
        fontFamily: INTER_FONT.bold,
        fontSize: 17,
        color: wizardColors.dark,
        flex: 1,
    },
    pickerList: {
        maxHeight: 360,
    },
    pickerRow: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingHorizontal: 20,
        paddingVertical: 14,
        borderBottomWidth: 1,
        borderBottomColor: '#F0F0EA',
        backgroundColor: wizardColors.white,
    },
    pickerRowSelected: {
        backgroundColor: '#F5F5F0',
    },
    pickerRowLabel: {
        flex: 1,
        fontFamily: INTER_FONT.medium,
        fontSize: 15,
        color: wizardColors.dark,
        marginRight: 12,
    },
    pickerRowLabelSelected: {
        fontFamily: INTER_FONT.bold,
    },
    pickerEmpty: {
        padding: 32,
        alignItems: 'center',
    },
    pickerEmptyText: {
        fontFamily: INTER_FONT.medium,
        fontSize: 14,
        color: wizardColors.subtle,
        textAlign: 'center',
    },
});
