import { Dimensions, Platform, StatusBar, StyleSheet } from 'react-native';

const { width } = Dimensions.get('window');

export const propertiesStyles = StyleSheet.create({
    safeArea: {
        flex: 1,
        backgroundColor: '#FFFFFF',
        paddingTop: Platform.OS === 'android' ? StatusBar.currentHeight : 0,
    },
    container: { flex: 1, backgroundColor: '#FFFFFF' },

    header: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingHorizontal: 20,
        paddingTop: 10,
        paddingBottom: 20,
    },
    locationLabel: { fontSize: 12, color: '#888', marginBottom: 4 },
    locationSelector: { flexDirection: 'row', alignItems: 'center' },
    locationText: { fontSize: 16, fontWeight: '700', color: '#000', marginHorizontal: 4 },
    iconCircle: {
        width: 44,
        height: 44,
        borderRadius: 22,
        borderWidth: 1,
        borderColor: '#EAEAEA',
        justifyContent: 'center',
        alignItems: 'center',
    },
    notificationDot: {
        position: 'absolute',
        top: 12,
        right: 12,
        width: 8,
        height: 8,
        backgroundColor: '#E63946',
        borderRadius: 4,
    },

    categoryContainer: { paddingHorizontal: 20, marginBottom: 24, gap: 16 },
    categoryWrap: { alignItems: 'center' },
    categoryIconBox: {
        width: 60,
        height: 60,
        borderRadius: 30,
        backgroundColor: '#F5F5F5',
        justifyContent: 'center',
        alignItems: 'center',
        marginBottom: 8,
    },
    categoryIconBoxActive: { backgroundColor: '#000' },
    categoryText: { fontSize: 13, color: '#888', fontWeight: '500' },
    categoryTextActive: { color: '#000', fontWeight: '700' },

    sectionHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingHorizontal: 20,
        marginBottom: 16,
    },
    sectionTitle: { fontSize: 18, fontWeight: '700', color: '#000' },
    seeAll: { fontSize: 14, color: '#888', fontWeight: '600' },

    horizontalList: { paddingHorizontal: 20, gap: 16, marginBottom: 24 },
    cardLarge: {
        width: width * 0.6,
        backgroundColor: '#FFF',
        borderRadius: 16,
        padding: 12,
        borderWidth: 1,
        borderColor: '#F0F0F0',
    },
    cardImageContainer: { position: 'relative', marginBottom: 12 },
    cardImageLarge: { width: '100%', height: 140, borderRadius: 12, backgroundColor: '#F0F0F0' },
    heartButton: {
        position: 'absolute',
        top: 8,
        right: 8,
        width: 32,
        height: 32,
        borderRadius: 16,
        backgroundColor: '#FFF',
        justifyContent: 'center',
        alignItems: 'center',
    },
    tagSmall: {
        position: 'absolute',
        bottom: 8,
        left: 8,
        backgroundColor: '#FFF',
        paddingHorizontal: 8,
        paddingVertical: 4,
        borderRadius: 6,
    },
    tagTextSmall: { fontSize: 10, fontWeight: '700', color: '#000' },
    cardTitle: { fontSize: 16, fontWeight: '700', color: '#000', marginBottom: 4 },
    cardLocationRow: { flexDirection: 'row', alignItems: 'center', marginBottom: 8 },
    cardLocationText: { fontSize: 12, color: '#888', marginLeft: 4, flex: 1 },
    cardPrice: { fontSize: 16, fontWeight: '800', color: '#E63946' },
    cardPricePeriod: { fontSize: 12, color: '#888', fontWeight: '500' },

    verticalList: { paddingHorizontal: 20, gap: 16 },
    cardSmall: {
        flexDirection: 'row',
        backgroundColor: '#FFF',
        borderRadius: 16,
        padding: 12,
        borderWidth: 1,
        borderColor: '#F0F0F0',
    },
    cardImageContainerSmall: { position: 'relative', marginRight: 12 },
    cardImageSmall: { width: 100, height: 100, borderRadius: 12, backgroundColor: '#F0F0F0' },
    heartButtonSmall: {
        position: 'absolute',
        top: 6,
        right: 6,
        width: 24,
        height: 24,
        borderRadius: 12,
        backgroundColor: '#FFF',
        justifyContent: 'center',
        alignItems: 'center',
    },
    cardSmallContent: { flex: 1, justifyContent: 'center' },
    tagTextSmallBox: { fontSize: 10, fontWeight: '700', color: '#888', marginBottom: 4 },

    heroContainer: { position: 'relative' },
    heroImage: { width: '100%', height: 320, backgroundColor: '#F0F0F0' },
    heroNav: {
        position: 'absolute',
        top: Platform.OS === 'android' ? StatusBar.currentHeight + 10 : 40,
        left: 0,
        right: 0,
        flexDirection: 'row',
        justifyContent: 'space-between',
        paddingHorizontal: 20,
    },
    circleBtn: {
        width: 40,
        height: 40,
        borderRadius: 20,
        backgroundColor: '#FFF',
        justifyContent: 'center',
        alignItems: 'center',
    },
    heroNavActions: { flexDirection: 'row', gap: 10 },

    thumbnailContainer: {
        flexDirection: 'row',
        justifyContent: 'center',
        gap: 12,
        marginTop: -35,
        paddingHorizontal: 20,
        zIndex: 10,
    },
    thumbnailWrap: {
        width: 70,
        height: 70,
        borderRadius: 12,
        backgroundColor: '#FFF',
        padding: 4,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.1,
        shadowRadius: 8,
        elevation: 5,
    },
    thumbnail: { width: '100%', height: '100%', borderRadius: 8, backgroundColor: '#F0F0F0' },
    thumbnailOverlay: {
        position: 'absolute',
        top: 4,
        left: 4,
        right: 4,
        bottom: 4,
        backgroundColor: 'rgba(0,0,0,0.5)',
        borderRadius: 8,
        justifyContent: 'center',
        alignItems: 'center',
    },
    thumbnailOverlayText: { color: '#FFF', fontWeight: '700', fontSize: 16 },

    detailsBody: { padding: 20, marginTop: 10 },
    detailsHeaderRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'flex-end',
        marginBottom: 8,
    },
    detailsPrice: { fontSize: 22, fontWeight: '800', color: '#E63946' },
    detailsTitle: { fontSize: 24, fontWeight: '800', color: '#000', marginBottom: 8 },
    detailsLocationText: { fontSize: 14, color: '#888', marginLeft: 6 },

    specsContainer: { flexDirection: 'row', gap: 16, marginVertical: 20 },
    specBox: {
        flex: 1,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: '#FFF',
        borderWidth: 1,
        borderColor: '#F0F0F0',
        borderRadius: 12,
        paddingVertical: 12,
        gap: 8,
    },
    specLabel: { fontSize: 14, fontWeight: '700', color: '#000' },

    sectionTitleDetails: { fontSize: 18, fontWeight: '700', color: '#000', marginBottom: 12 },
    descriptionText: { fontSize: 14, color: '#888', lineHeight: 22, marginBottom: 24 },
    readMore: { color: '#000', fontWeight: '700' },

    brokerContainer: { flexDirection: 'row', alignItems: 'center', marginBottom: 40 },
    brokerImage: { width: 50, height: 50, borderRadius: 25, marginRight: 12, backgroundColor: '#F0F0F0' },
    brokerInfo: { flex: 1 },
    brokerName: { fontSize: 16, fontWeight: '700', color: '#000' },
    brokerPhone: { fontSize: 12, color: '#888', marginTop: 2 },
    brokerActions: { flexDirection: 'row', gap: 12 },
    actionCircle: {
        width: 40,
        height: 40,
        borderRadius: 20,
        backgroundColor: '#000',
        justifyContent: 'center',
        alignItems: 'center',
    },

    bottomBar: {
        position: 'absolute',
        bottom: 0,
        left: 0,
        right: 0,
        backgroundColor: '#FFF',
        paddingHorizontal: 20,
        paddingTop: 16,
        paddingBottom: 32,
        borderTopWidth: 1,
        borderTopColor: '#F0F0F0',
    },
    bookButton: {
        backgroundColor: '#000',
        borderRadius: 30,
        height: 56,
        justifyContent: 'center',
        alignItems: 'center',
    },
    bookButtonText: { color: '#FFF', fontSize: 16, fontWeight: '700' },

    centerState: { flex: 1, justifyContent: 'center', alignItems: 'center', padding: 24 },
    errorText: { fontSize: 15, color: '#E63946', textAlign: 'center', marginBottom: 16 },
    retryButton: {
        backgroundColor: '#000',
        paddingHorizontal: 24,
        paddingVertical: 12,
        borderRadius: 24,
    },
    retryButtonText: { color: '#FFF', fontWeight: '700' },
    emptyText: { fontSize: 15, color: '#888', textAlign: 'center' },
});
