import { Platform, StyleSheet } from 'react-native';

import { INTER_FONT } from '../../../theme/interFontCdn';
import { PROPERTIES_SCREEN_BG } from '../constants/propertyListFilters';

export const propertiesListStyles = StyleSheet.create({
    loadingContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: PROPERTIES_SCREEN_BG,
    },
    list: {
        flex: 1,
    },
    listContainer: {
        paddingBottom: 32,
        flexGrow: 1,
    },
    listContainerEmpty: {
        flexGrow: 1,
    },
    headerContainer: {
        paddingHorizontal: 20,
        paddingTop: 4,
        paddingBottom: 8,
    },
    topBar: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
    },
    screenTitle: {
        fontSize: 22,
        fontFamily: INTER_FONT.bold,
        color: '#111',
    },
    topBarActions: {
        flexDirection: 'row',
        gap: 12,
    },
    actionBtnLight: {
        width: 44,
        height: 44,
        borderRadius: 16,
        backgroundColor: '#FFF',
        justifyContent: 'center',
        alignItems: 'center',
        borderWidth: 1,
        borderColor: '#EAEAEA',
    },
    actionBtnDark: {
        width: 44,
        height: 44,
        borderRadius: 16,
        backgroundColor: '#111',
        justifyContent: 'center',
        alignItems: 'center',
        ...Platform.select({
            android: { elevation: 4 },
            ios: {
                shadowColor: '#000',
                shadowOffset: { width: 0, height: 4 },
                shadowOpacity: 0.2,
                shadowRadius: 6,
            },
        }),
    },
    summarySection: {
        marginBottom: 24,
    },
    summaryLargeNumber: {
        fontSize: 30,
        fontFamily: INTER_FONT.bold,
        color: '#111',
        lineHeight: 56,
    },
    summarySubtext: {
        fontSize: 14,
        fontFamily: INTER_FONT.medium,
        color: '#888',
        marginTop: 4,
    },
    statusSegmentTrack: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#EFEEE9',
        borderRadius: 24,
        padding: 4,
        marginBottom: 16,
        gap: 2,
    },
    statusSegmentItem: {
        flex: 1,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        paddingHorizontal: 6,
        paddingVertical: 8,
        borderRadius: 20,
        minWidth: 0,
    },
    statusSegmentItemActive: {
        backgroundColor: '#FFF',
        ...Platform.select({
            android: { elevation: 2 },
            ios: {
                shadowColor: '#000',
                shadowOffset: { width: 0, height: 1 },
                shadowOpacity: 0.06,
                shadowRadius: 3,
            },
        }),
    },
    statusSegmentLabel: {
        fontSize: 13,
        fontFamily: INTER_FONT.semiBold,
        color: '#9CA3AF',
    },
    statusSegmentLabelActive: {
        fontFamily: INTER_FONT.bold,
        color: '#111827',
    },
    statusSegmentCount: {
        fontSize: 11,
        fontFamily: INTER_FONT.medium,
        color: '#9CA3AF',
        marginLeft: 5,
    },
    statusSegmentCountActive: {
        color: '#9CA3AF',
    },
    filterScroll: {
        marginBottom: 16,
        marginHorizontal: -20,
    },
    filterScrollContent: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 10,
        paddingHorizontal: 20,
    },
    filterPillDark: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal: 16,
        paddingVertical: 10,
        borderRadius: 20,
        backgroundColor: '#111',
        flexShrink: 0,
    },
    filterTextActiveDark: {
        fontSize: 13,
        fontFamily: INTER_FONT.semiBold,
        color: '#FFF',
    },
    filterCountDark: {
        fontSize: 11,
        fontFamily: INTER_FONT.bold,
        color: '#FFF',
        opacity: 0.8,
        marginLeft: 6,
        backgroundColor: 'rgba(255,255,255,0.2)',
        paddingHorizontal: 6,
        paddingVertical: 2,
        borderRadius: 10,
    },
    filterPillOutline: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal: 16,
        paddingVertical: 10,
        borderRadius: 20,
        backgroundColor: '#FFF',
        borderWidth: 1,
        borderColor: '#EAEAEA',
        flexShrink: 0,
    },
    filterTextOutline: {
        fontSize: 13,
        fontFamily: INTER_FONT.semiBold,
        color: '#111',
    },
    filterCountOutline: {
        fontSize: 11,
        fontFamily: INTER_FONT.bold,
        color: '#888',
        marginLeft: 6,
    },
    card: {
        backgroundColor: '#FFF',
        marginHorizontal: 20,
        marginBottom: 12,
        borderRadius: 16,
        padding: 14,
        borderWidth: 1,
        borderColor: '#EBEBEB',
        ...Platform.select({
            android: { elevation: 1 },
            ios: {
                shadowColor: '#000',
                shadowOffset: { width: 0, height: 2 },
                shadowOpacity: 0.04,
                shadowRadius: 8,
            },
        }),
    },
    cardTop: {
        flexDirection: 'row',
        alignItems: 'flex-start',
    },
    iconBox: {
        width: 56,
        height: 56,
        backgroundColor: '#F5F5F0',
        borderRadius: 12,
        justifyContent: 'center',
        alignItems: 'center',
        marginRight: 12,
        overflow: 'hidden',
    },
    thumbImage: {
        width: '100%',
        height: '100%',
    },
    cardContent: {
        flex: 1,
        minWidth: 0,
    },
    titleRow: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 5,
        gap: 8,
    },
    propertyTitle: {
        fontSize: 14,
        fontFamily: INTER_FONT.bold,
        color: '#111827',
        flex: 1,
        minWidth: 0,
        letterSpacing: -0.2,
    },
    statusBadge: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#E8F5E9',
        paddingHorizontal: 7,
        paddingVertical: 3,
        borderRadius: 20,
        flexShrink: 0,
    },
    statusDot: {
        width: 5,
        height: 5,
        borderRadius: 2.5,
        backgroundColor: '#2E7D32',
        marginRight: 4,
    },
    statusText: {
        fontSize: 10,
        fontFamily: INTER_FONT.semiBold,
        color: '#2E7D32',
    },
    statusBadgeVacant: {
        backgroundColor: '#FFF3E0',
    },
    statusDotVacant: {
        backgroundColor: '#E76F51',
    },
    statusTextVacant: {
        color: '#E65100',
    },
    statusBadgePart: {
        backgroundColor: '#E3F2FD',
    },
    statusDotPart: {
        backgroundColor: '#1976D2',
    },
    statusTextPart: {
        color: '#1565C0',
    },
    locationRow: {
        flexDirection: 'row',
        alignItems: 'flex-start',
        marginBottom: 8,
        gap: 8,
    },
    locationLeft: {
        flexDirection: 'row',
        alignItems: 'flex-start',
        flex: 1,
        minWidth: 0,
        gap: 4,
        paddingTop: 1,
    },
    locationText: {
        fontSize: 12,
        fontFamily: INTER_FONT.regular,
        color: '#9CA3AF',
        flex: 1,
        minWidth: 0,
        lineHeight: 16,
    },
    locationBadgesColumn: {
        flexDirection: 'column',
        alignItems: 'flex-end',
        gap: 4,
        flexShrink: 0,
        maxWidth: 118,
    },
    typeBadge: {
        backgroundColor: '#F9FAFB',
        paddingHorizontal: 7,
        paddingVertical: 3,
        borderRadius: 20,
        borderWidth: 1,
        borderColor: '#E5E7EB',
        flexShrink: 0,
    },
    typeBadgeText: {
        fontSize: 9,
        fontFamily: INTER_FONT.semiBold,
        color: '#6B7280',
    },
    licenseBadge: {
        backgroundColor: '#F3F4F6',
        paddingHorizontal: 7,
        paddingVertical: 3,
        borderRadius: 20,
        flexShrink: 0,
    },
    licenseText: {
        fontSize: 9,
        fontFamily: INTER_FONT.semiBold,
        color: '#4B5563',
    },
    specsRow: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        gap: 8,
    },
    specsLeft: {
        flexDirection: 'row',
        alignItems: 'center',
        flex: 1,
        minWidth: 0,
        gap: 8,
        flexWrap: 'wrap',
    },
    specSegment: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 8,
        flexShrink: 0,
    },
    specItem: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 3,
    },
    specDivider: {
        width: 1,
        height: 12,
        backgroundColor: '#E5E7EB',
    },
    specText: {
        fontSize: 11,
        fontFamily: INTER_FONT.medium,
        color: '#9CA3AF',
    },
    priceText: {
        fontSize: 12,
        fontFamily: INTER_FONT.bold,
        color: '#111827',
        flexShrink: 0,
    },
    priceTextLong: {
        fontSize: 10,
    },
    pricePeriod: {
        fontSize: 11,
        fontFamily: INTER_FONT.regular,
        color: '#FF0000',
        fontWeight: 'bold',
    },
    divider: {
        height: 1,
        backgroundColor: '#F0F0F0',
        marginTop: 12,
        marginBottom: 10,
    },
    cardFooter: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
    },
    tenantRow: {
        flexDirection: 'row',
        alignItems: 'center',
        flex: 1,
        marginRight: 8,
    },
    tenantDot: {
        width: 5,
        height: 5,
        borderRadius: 2.5,
        backgroundColor: '#2E7D32',
    },
    tenantName: {
        fontSize: 12,
        fontFamily: INTER_FONT.semiBold,
        color: '#111827',
        marginLeft: 6,
        flexShrink: 1,
    },
    paidStatus: {
        fontSize: 12,
        fontFamily: INTER_FONT.regular,
        color: '#9CA3AF',
    },
    vacantFooterText: {
        fontSize: 12,
        fontFamily: INTER_FONT.regular,
        color: '#9CA3AF',
        fontStyle: 'italic',
    },
    centerState: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        padding: 24,
        backgroundColor: PROPERTIES_SCREEN_BG,
    },
    errorText: {
        fontSize: 15,
        fontFamily: INTER_FONT.medium,
        color: '#E63946',
        textAlign: 'center',
        marginBottom: 16,
    },
    retryButton: {
        backgroundColor: '#000',
        paddingHorizontal: 24,
        paddingVertical: 12,
        borderRadius: 24,
    },
    retryButtonText: {
        color: '#FFF',
        fontFamily: INTER_FONT.bold,
    },
    emptyText: {
        fontSize: 15,
        fontFamily: INTER_FONT.medium,
        color: '#888',
        textAlign: 'center',
        paddingHorizontal: 20,
    },
});
